name: agahi_app
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=2.19.3 <3.0.0'



dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  get_storage: ^2.1.1
  get: ^4.6.5
  accordion: ^2.5.1
  timeago: ^3.4.0
  web_socket_channel: ^2.4.0
  image_picker: ^0.8.7+5
  awesome_notifications: ^0.8.1
  carousel_slider: ^4.2.1
  url_launcher: ^6.1.11
  file_picker: ^5.3.0
  shamsi_date: ^1.0.1
  dots_indicator: ^3.0.0
  intl: ^0.18.0
  flutter_map: ^6.1.0
  share_plus: ^7.2.2
  latlong2: ^0.9.0
  geolocator: ^10.1.0
  firebase_core: ^2.25.4
  image_cropper: ^5.0.1
  #flutter_offline: "^3.0.1"
  restart_app: ^1.1.3
  firebase_messaging: ^14.7.15
  firebase_dynamic_links: ^5.4.13
  go_router: ^10.1.0 
  uni_links: ^0.5.1
  connectivity_plus: ^4.0.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  change_app_package_name: ^1.1.0


  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: false
  image_path: "lib/assets/images/ic_logo.jpg"
  min_sdk_android: 21 

flutter:


  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
  assets:
    - assets/images/
    # To add custom fonts to your application, add a fonts section here,
    # in this "flutter" section. Each entry in this list should have a
    # "family" key with the font family name, and a "fonts" key with a
    # list giving the asset and other descriptors for the font. For
    # example:
  fonts:
    - family: iransans
      fonts:
        - asset: assets/font/iransans.ttf